// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wachari.Api.Data;

#nullable disable

namespace Wachari.Api.Migrations
{
    [DbContext(typeof(WachariDbContext))]
    partial class WachariDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Wachari.Api.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaItems");

                    b.HasDiscriminator<string>("Type").HasValue("MediaItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wachari.Api.Models.Movie", b =>
                {
                    b.HasBaseType("Wachari.Api.Models.MediaItem");

                    b.Property<int>("RuntimeMinutes")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("movie");
                });

            modelBuilder.Entity("Wachari.Api.Models.TvShow", b =>
                {
                    b.HasBaseType("Wachari.Api.Models.MediaItem");

                    b.Property<int>("NumberOfEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfSeasons")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("tvShow");
                });
#pragma warning restore 612, 618
        }
    }
}
